### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by jordi-s** [giovannicaligaris/iwork10-pro-linux#2]
Please, could you post if bluetooth works out of the box (or not) with Ubuntu 19.10?

Kernel 4.19 requires a one-line patch and a recompilation to enable support for a user space driver. Has the process become easier with kernel 5.3?

Many thanks in advance!

**Comment by junocomp** [comment]
It does work. 

If you're using Ubuntu 18.04 I would advise you install linux-generic-hwe-18.04-edge and linux-tools-generic-hwe-18.04-edge and restart the tablet.

**Comment by jordi-s** [comment]
Many thanks for the suggestion! It really makes bluetooth work on Ubuntu 18.04 without further work.
